pipeline {
  agent any
  
  stages {
    stage('Clone Git Repository') {
            steps {
                script {
                    sh 'rm -rf dev-week'
                    checkout scm // checkout based on the configured credentials in the current Jenkins Job
                    sh 'pwd'
                }
            }
        }
    stage('build') {
      steps {
        sh 'pip3 install -r requirements.txt'
      }
    }
    stage('test') {
      steps {
        sh '/opt/homebrew/bin/pytest test.py'
      }    
    }
    stage('deploy') {
      steps {
        sh 'nohup python3 app.py > app.log 2>&1 &'
       // sh 'nohup python3 -m flask run --host=0.0.0.0 --port=5001 > flask_app.log 2>&1 &'
      }
    }
  }
}